// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// pi_ij_cpp
Rcpp::NumericMatrix pi_ij_cpp(Rcpp::NumericVector m, double N_n1, Rcpp::NumericVector N_m_n1, Rcpp::NumericMatrix N_m_m_n1);
RcppExport SEXP ACSampling_pi_ij_cpp(SEXP mSEXP, SEXP N_n1SEXP, SEXP N_m_n1SEXP, SEXP N_m_m_n1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type N_n1(N_n1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type N_m_n1(N_m_n1SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type N_m_m_n1(N_m_m_n1SEXP);
    __result = Rcpp::wrap(pi_ij_cpp(m, N_n1, N_m_n1, N_m_m_n1));
    return __result;
END_RCPP
}
// var_t_HT_cpp
Rcpp::NumericMatrix var_t_HT_cpp(Rcpp::NumericVector m, Rcpp::NumericVector pi_i_values, Rcpp::NumericMatrix pi_ij_values, Rcpp::NumericVector y);
RcppExport SEXP ACSampling_var_t_HT_cpp(SEXP mSEXP, SEXP pi_i_valuesSEXP, SEXP pi_ij_valuesSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pi_i_values(pi_i_valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pi_ij_values(pi_ij_valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(var_t_HT_cpp(m, pi_i_values, pi_ij_values, y));
    return __result;
END_RCPP
}
// R_hat_cpp
Rcpp::NumericMatrix R_hat_cpp(Rcpp::NumericVector y_hat, Rcpp::NumericVector pi_i_values, Rcpp::NumericMatrix pi_ij_values);
RcppExport SEXP ACSampling_R_hat_cpp(SEXP y_hatSEXP, SEXP pi_i_valuesSEXP, SEXP pi_ij_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_hat(y_hatSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pi_i_values(pi_i_valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pi_ij_values(pi_ij_valuesSEXP);
    __result = Rcpp::wrap(R_hat_cpp(y_hat, pi_i_values, pi_ij_values));
    return __result;
END_RCPP
}
